### ISSUE TITLE
Ability to resize window.

### ISSUE THREAD

**Issue by Ezmyrelda** [andersfischernielsen/Traktor-Transition-Finder#12]
I would like the ability to resize the window and maximize it. That is doubleclick on the window bar and maximize the window to the display. At home I use multiple displays and have a display in portrait mode and it would be nice to have the window use all available space.

This should of course be filed or tagged or whatever under enhancement request.

**Comment by andersfischernielsen** [comment]
:+1:

**Comment by andersfischernielsen** [comment]
Fixed in a47f4fd539811747d15b6b01e425b3313dfd02b3.
