### ISSUE TITLE
Application damaged or broken.

### ISSUE THREAD

**Issue by dharit-tan** [andersfischernielsen/Traktor-Transition-Finder#17]
When I try to open the application, I receive this error:
![screen shot 2015-11-18 at 8 31 27 pm](https://cloud.githubusercontent.com/assets/3893871/11262371/6c192142-8e33-11e5-8cef-4313c322e610.png)
Running OSX 10.9.5.

**Comment by andersfischernielsen** [comment]
Could I get you to right click on the app and select "Get Info..." and check the version number? :)

**Comment by dharit-tan** [comment]
1.1.2

**Comment by andersfischernielsen** [comment]
I fixed the release. It should work if you redownload. :)

**Comment by andersfischernielsen** [comment]
https://github.com/andersfischernielsen/TraktorAutoNextSong/releases/tag/1.1.2

**Comment by dharit-tan** [comment]
Sweet, works now thanks a bunch!
