### ISSUE TITLE
UX - Implement back button / breadcrumb history

### ISSUE THREAD

**Issue by Marak** [andersfischernielsen/Traktor-Transition-Finder#18]
As per #8, when clicking on a track in the TraktorAutoNextSong, it will now load auto-suggestions for that track, awesome!

What would be good, is have the ability to go back and see the results for the previous track.

What happens is that I might click on a track by accident ( or on purpose ) but want to go back...the only way to do that right now would be re-dragging the track back into the drop down...not so awesome. Trying to minimize the amount of times I have to drag into the TraktorAutoNextSong.

I'm thinking this should be relatively easy to implement. You should only need to keep a small array in memory. I would recommend putting a max size on the array and popping off the first elements when you hit the max ( this will ensure we don't get memory leaks if the app is left on for a long time )

**Comment by andersfischernielsen** [comment]
This has been finalised in 3c772f3e3d5d373b0aa30a992af2ef294bd37438
