### ISSUE TITLE
UI alignment - better full screen view

### ISSUE THREAD

**Issue by emmaarfelt** [andersfischernielsen/Traktor-Transition-Finder#21]
The tempo of the song, you are looking up stands to the left in the window and key to the right. But the results are the opposite - tempo to the right and key to the left. This would be nice if they were the same. 

Also, when dragging the window, the alignment of the tempo in the search results is far to the left - almost at the corner of the window. Would be nice if they were centered.

**Comment by emmaarfelt** [comment]
![traktor_auto_next_song](https://cloud.githubusercontent.com/assets/9945700/11302306/f2a229ce-8f9c-11e5-8716-2cb16770df2f.png)

**Comment by andersfischernielsen** [comment]
This is fixed by editing the css styling of the app. Better bootstrap columns or flex box should be used.

**Comment by andersfischernielsen** [comment]
This is still an issue in fullscreen after reimplementing in Swift. The constraints need some work in the main view.

**Comment by andersfischernielsen** [comment]
Fullscreen has now been removed.
