### ISSUE TITLE
No Suggestions When Dropping Song

### ISSUE THREAD

**Issue by Oldzskool** [andersfischernielsen/Traktor-Transition-Finder#23]
Really want to try this app out but it doesn't seem to do anything for me.

When I drop a song from Traktor Collection Window into TraktorAutoNextSong nothing happens, I get no suggestions the app doesn't do anything.  It does seem to analyse the collection.nml which is just under 6mb and opens up fine.

Any help or suggestions as to where I am going wrong would be gratefully receibed, I am using a Macbook Pro mid 2012 on El Capitan and Traktor Pro 2.10.0

**Comment by andersfischernielsen** [comment]
Is the song analysed in Traktor?

**Comment by Oldzskool** [comment]
Yes all the songs I have are analysed in traktor. I analyse them all as soon as they are imported.

**Comment by andersfischernielsen** [comment]
Could you try again with the new release?

**Comment by Oldzskool** [comment]
I've just tried to run this new version (Traktor Transition Finder 1.3) on my Macbook Pro mid 2012 running El Capitan 10.11.6 but this error message "A Java Script Error Occurred In The Main Process" appears a couple of seconds after it begins to analyse collection.nml.

**Comment by andersfischernielsen** [comment]
What version of Traktor are you running?

**Comment by andersfischernielsen** [comment]
Still 2.10?

**Comment by andersfischernielsen** [comment]
And could I get you to post the full error message?

**Comment by Oldzskool** [comment]
Ok so I open up Traktor Transition Finder 1.3,  click to Open 'collection nml', navigate to Traktor 2.10.3 folder, navigate to collection.nml, then click open.  After a couple of seconds the following error message pops up as below.

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at parseKey (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:28:24)
    at parseToSong (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:76:66)
    at Array.map (native)
    at Function.parseCollection (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/app/graph.js:79:32)
    at buildGraph (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/app/main.js:58:41)
    at EventEmitter.ipc.on (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/app/main.js:37:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Users/Hardy/Desktop/TraktorTransitionFinder.app/Contents/Resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)

**Here's link to a screen shot in case thats any help:-**
https://cloud.githubusercontent.com/assets/16529395/18809639/14e15472-8279-11e6-9c50-7b72fda4c5c9.png

**Comment by Oldzskool** [comment]
Just to add.... once I click to open collection nml the little rainbow pinwheel spins before displaying the error message.  When I click "ok" on the error message the program shows the animated blue square from previous versions of Traktor Transition Finder but never concludes.

**Comment by andersfischernielsen** [comment]
The error happens because your collection.nml and the one I use for development purposes differ in structure. Which is odd, since I'm on the same version of Traktor. The only way I can fix it is if I see the way your collection in structured vs. mine, unfortunately.

**Comment by Oldzskool** [comment]
Ok understood... is this possible?

**Comment by MrKinsky** [comment]
would it helpfull for you, when i send you my collection file?

**Comment by qmclaugh** [comment]
I have the same issue, happy to share my 2.10.3 collection file if that is helpful.  Thanks so much!  This is a really needed app and I'd LOVE to try it out.

**Comment by jeffebauer** [comment]
I know this is an old thread, but I'm running into the same issues with Traktor 2.11.0 — 
<img width="532" alt="screen shot 2017-10-12 at 5 26 35 pm" src="https://user-images.githubusercontent.com/127044/31525065-8626c4a6-af72-11e7-85c1-c6fe12b9fc79.png">

Is this still under active development, or are my hopes dashed?

**Comment by TeeManTeeMan** [comment]
Same issue here – would love to try this in 2018! :D

**Comment by andersfischernielsen** [comment]
Could you try the new 1.3.5 release of the app?

**Comment by TeeManTeeMan** [comment]
I'd love to try it!

Where do I get it?

**Comment by andersfischernielsen** [comment]
https://github.com/andersfischernielsen/Traktor-Transition-Finder/releases

**Comment by tommytyker** [comment]
This is what I get with the new release. Out of memory? My file is 17.6MB

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3537636/57972682-170c8180-799e-11e9-9889-7f2ccf09c99a.png">

**Comment by TeeManTeeMan** [comment]
Doesn't work for me either (High Sierra 10.13.5) – thanks for the effort though!

**Comment by andersfischernielsen** [comment]
I haven't tested with libraries that big. It requires parsing XML through stream-based reading. 
I'll need to look into that. It's definitely been done before.

**Comment by andersfischernielsen** [comment]
Could you try with the updated release (same version number) https://github.com/andersfischernielsen/Traktor-Transition-Finder/releases? 
It implements streaming the XML, should fix the large library issues.

**Comment by TeeManTeeMan** [comment]
My collection.nml file is only 2-4 MB.

No error message this time but the the spinner just runs indefinitely and no results are shown.

**Comment by andersfischernielsen** [comment]
@TeeManTeeMan Is there any way for you to send me your collection? I'm having a hard time fixing this without seeing the errors that come up in a debugger.

**Comment by TeeManTeeMan** [comment]
Sure!
Where to?
I cannot attach it here as the file type is not supported.

**Comment by andersfischernielsen** [comment]
Can you zip it and then upload it?

**Comment by TeeManTeeMan** [comment]
Ofc ... I have added my Traktor2 and Traktor3 collection.nml file.

[Traktor2-collection.nml.zip](https://github.com/andersfischernielsen/Traktor-Transition-Finder/files/3201074/Traktor2-collection.nml.zip)
[Traktor3-collection.nml.zip](https://github.com/andersfischernielsen/Traktor-Transition-Finder/files/3201076/Traktor3-collection.nml.zip)

**Comment by andersfischernielsen** [comment]
I'll look into it 👍

**Comment by andersfischernielsen** [comment]
I found the issue, can load both your `v2` and `v3` collection and have updated the 1.3.5 release.
