### ISSUE TITLE
Traktor 2.10 compatibility?

### ISSUE THREAD

**Issue by louisemile** [andersfischernielsen/Traktor-Transition-Finder#24]
Hello, I love the idea behind the app you have created but am having trouble with dragging the tracks from my traktor collection into the app. Nothing happens when i drag them over?
I am using Traktor 2.10 and am wondering if it only works for earlier versions?

Thank you for your time,
Louis

**Comment by qmclaugh** [comment]
Same is true for me.  Anyone having luck with Traktor 2.10? Looks like there is a bug here.

And thank you for writing this app - seems super helpful, I am very excited to get it to run.  Thank you!

**Comment by andersfischernielsen** [comment]
Could you try to redownload the app and try again?

**Comment by louisemile** [comment]
Hey Anders!
I got this java script error when i tried to load my collection?

I hope the screen shot is of help!

[image: Inline image 1]

**Comment by andersfischernielsen** [comment]
Could you try the new 1.3.5 release of the app?
