### ISSUE TITLE
Windows prompt pop-up before start

### ISSUE THREAD

**Issue by emmaarfelt** [andersfischernielsen/Traktor-Transition-Finder#25]
When I start the app, I get two pop-up windows. The app is not working and will spend eternity on loading the collection. It never succeeds.  

![screen shot 2016-08-20 at 23 36 49](https://cloud.githubusercontent.com/assets/9945700/17834008/5a4d9986-672f-11e6-9676-8abc03fa7600.png)

![screen shot 2016-08-20 at 23 40 00](https://cloud.githubusercontent.com/assets/9945700/17834012/710d06ca-672f-11e6-8121-88d09f150ee1.png)

**Comment by andersfischernielsen** [comment]
This is due to the fact that you haven't got the mono runtime installed, which is a requirement for running the app (a fix is described in #28, but you can simply install it from the website of Mono).
