### ISSUE TITLE
Could you provide a macOS 10.13 version?

### ISSUE THREAD

**Issue by sandersantema** [andersfischernielsen/Traktor-Transition-Finder#37]
Or compilation instructions for 10.13 thanks!

**Comment by andersfischernielsen** [comment]
Does the 1.4 release not run on macOS 10.13? 
XCode is should build for all versions, as far as I can see.

**Comment by andersfischernielsen** [comment]
Can you try the 1.4.1 release at https://github.com/andersfischernielsen/Traktor-Transition-Finder/releases/tag/1.4.1?

It should be built to support Sierra and up.
