### ISSUE TITLE
Implement looking for half-tempo mixes

### ISSUE THREAD

**Issue by andersfischernielsen** [andersfischernielsen/Traktor-Transition-Finder#5]
The app should also check if mixing from a 140 BPM track to a 70 BPM track would give a nice result. 
This transition should preferably have a lower "rating" than "normal" mixes, since it's a bit more difficult to pull off when mixing.

**Comment by Marak** [comment]
+1

**Comment by andersfischernielsen** [comment]
Implemented in acbf5c789a2eb6e870cfcec0b797d6f9e75b80bc.
