### ISSUE TITLE
Auto-suggestion algorithm should accept input modifiers

### ISSUE THREAD

**Issue by Marak** [andersfischernielsen/Traktor-Transition-Finder#7]
When looking for a new track, users should be able to specify the "direction" in which they want to move.

I say "direction" as a single modifier, but in reality the direction can be defined by a Domain Specific Language.

Without getting into too many details about the DSL, we can assume a few simple input modifiers to start.

`UP Tempo` / `DOWN Tempo` - Next tracks should either increase or decrease in tempo

`UP Key` / `DOWN Key` -  Next tracks should either go up or down key

The idea here is that the auto-suggestion algorithm will add an additional weight to tracks which match the input modifier criteria. For example: If the user clicks `UP Tempo`, then the suggested tracks will all represent tracks which go up in tempo.

**Comment by Ezmyrelda** [comment]
This is something I would also like to see. I specifically am not really interested in the up or down key portion since key matching is the primary interest I have in the app, but I do generally tend to push the tempo up slowly over the course of my mixes.

**Comment by Marak** [comment]
To be clear, all input modifiers would be optional and only applied if the user specifically selected a modifier.
