### ISSUE TITLE
Clicking on a track in the AutoNextSong UI should load suggestions for that track

### ISSUE THREAD

**Issue by Marak** [andersfischernielsen/Traktor-Transition-Finder#8]
After loading the collection and then dragging a track to the drop area, tracks are auto-suggested. This is great!

I can find that track in my collection and load it on Traktor. That's easy.

I'm now playing the track which was auto-suggested. Next, I have to drag that file into the AutoNextSong UI. This seems a bit redundant.

What would be much easier here, is to be able to click on a track in the AutoNextSong UI, and have it load a new set of recommendations based on that track. I'm assuming all the data we need is already there?

You'd probably also want to implement a "Back" button in the AutoNextSong as well, so you could back to the last set of recommendations shown.

**Comment by andersfischernielsen** [comment]
Great idea! :+1:

**Comment by Marak** [comment]
Nice one!

I will download the latest version of the app later today ( after release? ) and try the new changes.

Thanks for the continued updates @andersfischernielsen !
