### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by dharit-tan** [andersfischernielsen/Traktor-Transition-Finder#9]
Running OSX 10.9.5, mid 2012 macbook pro. Traktor 2.10.0 13. 16GB RAM.

Received this error after selecting Traktor's collection.nml:
![screen shot 2015-11-10 at 9 22 42 pm](https://cloud.githubusercontent.com/assets/3893871/11084526/34154d68-87f1-11e5-848f-01c1c39017d5.png)

Really want to check this out!

**Comment by Marak** [comment]
@reedt - How large is your collection file?

If it's large, could you try with a smaller one?

**Comment by dharit-tan** [comment]
Mine was ~11MB, tried with older ~3MB one and it worked. Thanks.

**Comment by Marak** [comment]
@reedt -

That's just a band-aid for now.

@andersfischernielsen should re-open this issue.

We'll have to figure out the memory leak eventually. Hopefully it's a minor thing...

**Comment by andersfischernielsen** [comment]
@reedt Could I get you to download the app again and try with the ~11MB collection.nml again?

**Comment by dharit-tan** [comment]
Thanks for the quick turnaround. I tried again with my 11MB collection and received this error once:
![screen shot 2015-11-16 at 9 36 02 pm](https://cloud.githubusercontent.com/assets/3893871/11203596/25bcaf46-8caa-11e5-8ced-024303bf1c73.png)
after which the program seems to run indefinitely, stuck in the library analysis stage.

**Comment by andersfischernielsen** [comment]
@reedt I know it's a lot to ask, but could you email me your collection for testing? I promise I won't steal any songs. It's purely for bug fixing purposes. 
My email is andersfischern@me.com

**Comment by andersfischernielsen** [comment]
Should be fixed in https://github.com/andersfischernielsen/TraktorAutoNextSong/tree/1.1.1. :)

**Comment by andersfischernielsen** [comment]
It does take a while to parse the collection, though. But the app shouldn't fail now. 
On my Retina MacBook Pro (10 threads running while parsing) it takes about 5 min. to parse a 29 MB collection. 
I've added an issue about implementing a progress bar while parsing the collection. I'll get to it when I have the time. :)

**Comment by andersfischernielsen** [comment]
<img width="734" alt="screen shot 2015-11-18 at 19 06 23" src="https://cloud.githubusercontent.com/assets/5990738/11249542/c201d024-8e27-11e5-8438-a34981dc3e0f.png">
Running with a 29MB collection.
